using EggScript.Exceptions;
using EggScript.Parsing;
using EggScript.Parsing.Nodes.Expression;
using EggScript.Parsing.Nodes.Expression.Data;
using EggScript.Parsing.Nodes.Statement;

namespace EggScript.Runtime;

/// <summary>
/// Executes the EggScript program.
/// </summary>
internal static partial class Interpreter
{
	/// <summary>
	/// The interpreter's environment. Includes things like the scope, which contain variables.
	/// </summary>
	public static EggEnvironment Env { get; } = new();

	/// <summary>
	/// Runs an EggScript program based on the abstract syntax tree generated from the <see cref="Parser"/>.
	/// </summary>
	/// <param name="nodes">The list of nodes generated by the <see cref="Parser"/>.</param>
	/// <exception cref="EggRuntimeException">Thrown when a runtime error is encountered.</exception>
	public static void Execute(List<IStatementNode> nodes)
	{
		ExecuteNodes(nodes);
	}

	/// <summary>
	/// Executes a list of statement nodes.
	/// </summary>
	/// <param name="nodes">The statement nodes.</param>
	private static void ExecuteNodes(List<IStatementNode> nodes)
	{
		Env.PushScope();
		foreach (IStatementNode node in nodes)
		{
			ExecuteStatement(node);
		}
		Env.PopScope();
	}

	/// <summary>
	/// Executes a statement node.
	/// </summary>
	/// <param name="node">The statement node to execute.</param>
	/// <exception cref="EggRuntimeException">Thrown when an invalid node is detected.</exception>
	internal static void ExecuteStatement(IStatementNode node)
	{
		switch (node)
		{
			case PrintNode printNode:
				Console.WriteLine(printNode.Data.GetValue(Env).StringValue);
				break;

			case VarDeclarationNode varDecNode:
				Env.AddVariable(varDecNode.Name, varDecNode.Type, varDecNode.Constant);
				if (varDecNode.Initialized) Env.ModifyVariable(varDecNode.Name, varDecNode.Data.GetValue(Env), true);
				break;

			case VarAssignmentNode varAssNode:
				Env.ModifyVariable(varAssNode.Name, varAssNode.Data.GetValue(Env));
				break;

			case ConditionalNode conditionalNode:
				IDataNode condition = conditionalNode.Condition.GetValue(Env);
				if (condition is not BooleanNode result) throw new EggRuntimeException("If statement condition is not a boolean");

				if (result.Value) ExecuteStatement(conditionalNode.Body);
				else if (conditionalNode.Otherwise is not null) ExecuteStatement(conditionalNode.Otherwise);
				break;

			case BlockNode blockNode:
				Env.PushScope();
				foreach (IStatementNode statement in blockNode.Nodes)
				{
					ExecuteStatement(statement);
				}
				Env.PopScope();
				break;

			default:
				throw new EggRuntimeException($"Invalid node: {node.GetType().Name}");
		}
	}
}